package com.solvd.laba.enums;

public enum SubjectsNames {
    ENGLISH, ENGLISH_I, ENGLISH_II, REGIONAL_LANGUAGE, MATHS, SCIENCE, SOCIAL_SCIENCES, PHYSICAL_EDUCATION,
    COMPUTER_BASICS, ARTS, HISTORY, HISTORY_I, HISTORY_II, LINGUISTICS, LITERATURE, PERFORMING, PHILOSOPHY,
    RELIGION, VISUALS, ANTHROPOLOGY, ARCHAEOLOGY, CULTURE, ECONOMICS, GEOGRAPHY, POLITICS, PSYCHOLOGY,
    SOCIOLOGY, CHEMISTRY, LIFE, PHYSICS, SPACE, LOGIC, MATHEMATICS_II,
    STATISTICS, STATISTICS_II, SYSTEMS;
}
